version: '2'
services:
  bluetooth-audio:
    build: ./bluetooth-audio
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
      - snapcast:/var/cache/snapcast
  airplay:
    build: ./airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - snapcast:/var/cache/snapcast
  spotify:
    build: ./spotify
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
      - snapcast:/var/cache/snapcast
  fleet-supervisor:
    build: ./fleet-supervisor
    restart: on-failure
    network_mode: host
    privileged: true
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1
  snapcast-server:
    build: 
      context: ./snapcast-server
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
    volumes:
      - snapcast:/var/cache/snapcast
  snapcast-client:
    build: 
      context: ./snapcast-client
    restart: on-failure 
    network_mode: host 
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast
  upnp:
    build: ./upnp
    restart: on-failure 
    network_mode: host 
    ports:
      - 49494:49494
    volumes:
      - snapcast:/var/cache/snapcast
  wm8960-soundcard:
    build:
      context: ./wm8960-soundcard
    privileged: true
    restart: on-failure
    network_mode: host
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
volumes:
  spotifycache:
  bluetoothcache:
  snapcast:
